// Frontend/src/app/app-common/footer/footer.component.ts
// Angular
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<p class="copyright">Copyright © 2018 - <a href="http://www.istorms.net/">iStorms.</a> All Rights Reserved</p>

// Frontend/src/components/common/Footer.vue
<template>
    <div>
      <p class="copyright">Copyright © 2018 - <a href="http://www.istorms.net/">iStorms.</a> All Rights Reserved</p>
    </div>
</template>
<script>
export default{
}
</script>
<style lang='scss' scoped>
  .copyright {
    margin: 20px 0;
    font-size: 14px;
    color: #2d374b;
    a:hover {
      color: #36d1c4;
    }
  }
</style>
